=== valerioottani/LWEB-HOMEWORK3/xsd/acquisti_merch.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="acquisti_merch">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="acquisto" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:positiveInteger" minOccurs="1"/>
              <xs:element name="username" type="xs:string" minOccurs="1"/>
              <xs:element name="merchandise_id" type="xs:positiveInteger" minOccurs="1"/>
              <xs:element name="quantita" type="xs:positiveInteger" minOccurs="1"/>
              <xs:element name="data_acquisto" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== valerioottani/LWEB-HOMEWORK3/xml/acquisti_merch.xml
<?xml version='1.0' encoding='UTF-8'?>
<acquisti_merch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/acquisti_merch.xsd">
  <acquisto>
    <id>1</id>
    <username>utente</username>
    <merchandise_id>1</merchandise_id>
    <quantita>1</quantita>
    <data_acquisto/>
  </acquisto>
  <acquisto>
    <id>2</id>
    <username>utente</username>
    <merchandise_id>5</merchandise_id>
    <quantita>1</quantita>
    <data_acquisto/>
  </acquisto>
  <acquisto>
    <id>3</id>
    <username>alessia_monti</username>
    <merchandise_id>4</merchandise_id>
    <quantita>1</quantita>
    <data_acquisto/>
  </acquisto>
  <acquisto>
    <id>4</id>
    <username>federico_esposito</username>
    <merchandise_id>10</merchandise_id>
    <quantita>1</quantita>
    <data_acquisto/>
  </acquisto>
</acquisti_merch>
