=== valerioottani/LWEB-HOMEWORK3/xsd/playlist_tracce.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="playlist_tracce">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="associazione" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="playlist_id" type="xs:positiveInteger" minOccurs="1"/>
              <xs:element name="traccia_id" type="xs:positiveInteger" minOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== valerioottani/LWEB-HOMEWORK3/xml/playlist_tracce.xml
<?xml version="1.0" encoding="UTF-8"?>
<playlist_tracce xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/playlist_tracce.xsd">
  <associazione>
    <playlist_id>1</playlist_id>
    <traccia_id>1</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>1</playlist_id>
    <traccia_id>13</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>1</playlist_id>
    <traccia_id>19</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>2</playlist_id>
    <traccia_id>7</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>2</playlist_id>
    <traccia_id>9</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>2</playlist_id>
    <traccia_id>11</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>2</playlist_id>
    <traccia_id>17</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>3</playlist_id>
    <traccia_id>2</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>3</playlist_id>
    <traccia_id>8</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>3</playlist_id>
    <traccia_id>12</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>3</playlist_id>
    <traccia_id>23</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>101</playlist_id>
    <traccia_id>17</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>101</playlist_id>
    <traccia_id>9</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>101</playlist_id>
    <traccia_id>1</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>101</playlist_id>
    <traccia_id>7</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>101</playlist_id>
    <traccia_id>13</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>102</playlist_id>
    <traccia_id>11</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>102</playlist_id>
    <traccia_id>17</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>102</playlist_id>
    <traccia_id>2</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>102</playlist_id>
    <traccia_id>8</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>103</playlist_id>
    <traccia_id>7</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>103</playlist_id>
    <traccia_id>19</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>103</playlist_id>
    <traccia_id>23</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>103</playlist_id>
    <traccia_id>1</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>104</playlist_id>
    <traccia_id>1</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>104</playlist_id>
    <traccia_id>11</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>104</playlist_id>
    <traccia_id>17</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>104</playlist_id>
    <traccia_id>13</traccia_id>
  </associazione>
  <associazione>
    <playlist_id>104</playlist_id>
    <traccia_id>7</traccia_id>
  </associazione>
</playlist_tracce>
