=== valerioottani/LWEB-HOMEWORK3/xsd/posti_evento.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="posti_evento">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="posto" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:positiveInteger" minOccurs="1"/>
              <xs:element name="evento_id" type="xs:positiveInteger" minOccurs="1"/>
              <xs:element name="settore" type="xs:string" minOccurs="1"/>
              <xs:element name="numero_posto" type="xs:string" minOccurs="1"/>
              <xs:element name="prezzo" type="xs:decimal" minOccurs="1"/>
              <xs:element name="occupato" type="xs:boolean" minOccurs="1"/>
              <xs:element name="username" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== valerioottani/LWEB-HOMEWORK3/xml/posti_evento.xml
<?xml version='1.0' encoding='UTF-8'?>
<posti_evento xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/posti_evento.xsd">
  <posto>
    <id>1</id>
    <evento_id>1</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-1</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>2</id>
    <evento_id>1</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-2</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>3</id>
    <evento_id>1</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-3</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>1</occupato>
    <username/>
  </posto>
  <posto>
    <id>4</id>
    <evento_id>1</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-4</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>5</id>
    <evento_id>1</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-1</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>6</id>
    <evento_id>1</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-2</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>7</id>
    <evento_id>1</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-3</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>1</occupato>
    <username/>
  </posto>
  <posto>
    <id>8</id>
    <evento_id>1</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-4</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>9</id>
    <evento_id>1</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-1</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>10</id>
    <evento_id>1</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-2</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>11</id>
    <evento_id>1</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-3</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>1</occupato>
    <username/>
  </posto>
  <posto>
    <id>12</id>
    <evento_id>1</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-4</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>13</id>
    <evento_id>2</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-1</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>14</id>
    <evento_id>2</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-2</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>15</id>
    <evento_id>2</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-3</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>1</occupato>
    <username/>
  </posto>
  <posto>
    <id>16</id>
    <evento_id>2</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-4</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>17</id>
    <evento_id>2</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-1</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>18</id>
    <evento_id>2</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-2</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>19</id>
    <evento_id>2</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-3</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>1</occupato>
    <username/>
  </posto>
  <posto>
    <id>20</id>
    <evento_id>2</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-4</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>21</id>
    <evento_id>2</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-1</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>22</id>
    <evento_id>2</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-2</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>23</id>
    <evento_id>2</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-3</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>1</occupato>
    <username/>
  </posto>
  <posto>
    <id>24</id>
    <evento_id>2</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-4</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>25</id>
    <evento_id>3</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-1</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>26</id>
    <evento_id>3</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-2</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>27</id>
    <evento_id>3</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-3</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>1</occupato>
    <username/>
  </posto>
  <posto>
    <id>28</id>
    <evento_id>3</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-4</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>29</id>
    <evento_id>3</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-1</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>30</id>
    <evento_id>3</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-2</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>31</id>
    <evento_id>3</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-3</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>1</occupato>
    <username/>
  </posto>
  <posto>
    <id>32</id>
    <evento_id>3</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-4</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>33</id>
    <evento_id>3</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-1</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>34</id>
    <evento_id>3</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-2</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>35</id>
    <evento_id>3</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-3</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>1</occupato>
    <username/>
  </posto>
  <posto>
    <id>36</id>
    <evento_id>3</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-4</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>37</id>
    <evento_id>4</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-1</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>38</id>
    <evento_id>4</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-2</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>39</id>
    <evento_id>4</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-3</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>1</occupato>
    <username/>
  </posto>
  <posto>
    <id>40</id>
    <evento_id>4</evento_id>
    <settore>Parterre Standing</settore>
    <numero_posto>PAR-4</numero_posto>
    <prezzo>35.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>41</id>
    <evento_id>4</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-1</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>42</id>
    <evento_id>4</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-2</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>43</id>
    <evento_id>4</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-3</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>1</occupato>
    <username/>
  </posto>
  <posto>
    <id>44</id>
    <evento_id>4</evento_id>
    <settore>Tribuna VIP Numerata</settore>
    <numero_posto>TRI-4</numero_posto>
    <prezzo>65.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
    <id>45</id>
    <evento_id>4</evento_id>
    <settore>Primo Anello Laterale</settore>
    <numero_posto>PRI-1</numero_posto>
    <prezzo>45.00</prezzo>
    <occupato>0</occupato>
    <username/>
  </posto>
  <posto>
